import "./globals.css";
import "ui/styles.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useAuth, useSession } from "@clerk/nextjs";
import { createClient } from "@supabase/supabase-js";

import { Navbar } from "ui";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={`bg-gray-900 flex ${inter.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
